### ISSUE TITLE
--pool param explaination

### ISSUE THREAD

**Issue by onisoc** [8lecramm/derohe-proxy#2]
Hello,

I would like to contact you to ask about --pool param but there is no direct contact. So i submit issue here.
Could you please explain more details about --pool param? I'm now running your proxy withou any options, only daemon address. In my mind, i would like to combine small workers with low hashrate to one workers with high hashrate. Is is possible?

**Comment by 8lecramm** [comment]
Hi,
since multi wallet support, you can add miners that use different wallet addresses.
Each mining template is tuned for the miner. That means the keyhash (miner address) is replaced.
When pool mining, it is not a good idea to replace the keyhash. The results submitted by the proxy are rejected by the pool, due to a "keyhash error".
The `--pool` option just disables the replacement of the keyhash.
For solo mining, you're good to go without any option.

You cannot combine miners to one big miner. Each miner is treated as a solo miner. But it doesn't matter.
Here is an (theoretical) example:

**NW difficulty:** 90,000 H/s
**Miner:** 1x 900 H/s
Miner finds a block **every 100 seconds**

**NW difficulty:** 90,000 H/s
**Miners:** 3x 300 H/s
**Each** miner finds a block **every 300 seconds**
3 blocks every 300 seconds = 1 block per 100 seconds on average.

There is no difference in rewards, but it takes longer for each miner to find a block.

**Comment by onisoc** [comment]
Thank you very much for detailed response ;) So there is noway custers all miners as if they were a single machine, right?

**Comment by 8lecramm** [comment]
The daemon to which the proxy is connected sees only a single miner. It doesn’t matter how many miners are connected to the proxy.

**Comment by onisoc** [comment]
Thank you 8lecramm. I have another question.

Miner 1 mines with address A, connect to Proxy
Miner 2 mines with address B, connect to Proxy

Is it possible to proxy submit results from miner A and B to pool with defined address C?
It means address C will be rewarded instead miners' addresses.

**Comment by 8lecramm** [comment]
Done, this feature has just been added.

`--wallet-address=deroi.....`

This will use the defined wallet address for all connections.

**Comment by onisoc** [comment]
Best dev ever ;) Thanks man.
